name = "OptParams"
uuid = "15ebdc6a-d3d6-11e8-3620-6bd19035659b"
authors = ["Taylor McDonnell <taylor.golden.mcdonnell@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
